name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run tests
      run: make test

    - name: Setup terraform
      run: make bin/terraform

    - name: Populate GCP RO secret
      run: echo "$TERRAFORM_GCP_RO" > /tmp/terraform-ro.json
      env:
        TERRAFORM_GCP_RO: ${{secrets.TERRAFORM_GCP_RO}}

    - name: Terraform plan
      run: make plan
      env:
        GOOGLE_APPLICATION_CREDENTIALS: '/tmp/terraform-ro.json'

    - name: Populate GCP RW secret
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo "$TERRAFORM_GCP_RW" > /tmp/terraform-rw.json
      env:
        TERRAFORM_GCP_RW: ${{secrets.TERRAFORM_GCP_RW}}

    # On push to master, apply terraform changes
    - name: Terraform apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: make force-apply
      env:
        GOOGLE_APPLICATION_CREDENTIALS: '/tmp/terraform-rw.json'
